# -*- coding: utf-8 -*-
"""Numpy 1-dars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rN3V63qez9OkZ2vL1wH2pvFOxl3DgrKr

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. (NumPy kutubxonasi)

### NumPy kutubxonasini chaqirib olish
"""

import numpy as np

"""### Python list bilan NumPy kutubxonasidagi massivlar (arraylar) hisoblashlari orasidagi farqni ko'ramiz."""

my_list = list(range(100000)) # python list 0~99999 -->Normal
my_array = np.array(range(100000)) # numpy array(massiv) 0~99999 --> Vektorlashgan

# Commented out IPython magic to ensure Python compatibility.
# %time for _ in range(10): [x*2 for x in my_list] # Normal

# Commented out IPython magic to ensure Python compatibility.
# %time for _ in range(10): my_array*2 # Vektorlashgan

74.1/3.23

"""# List va Array,NumPy Array,NumPyda massivlar yaratish."""

data1=[3.5,45,12,45,12] #list
arr1=np.array(data1) # array1
arr1

data2=(4,56,12,44,32,12)
arr2=np.array(data2)
arr2

arr1.ndim # array1 ning o'lchami

arr2.ndim # array2 ning o'lchami

data3=[[14,44,32,80],[43,23,7,89]] # list ichidagi list (nested list)
arr3=np.array(data3) # array3
arr3

arr3.ndim

data4=[["Mushuk",2,"O'rik"],["Shaftoli","Behi","Olma"],[45,12,32]]
arr4=np.array(data4)
arr4

arr4.ndim

data4=[[23,64,53],[76,56,54],[45,12,32]]
arr4=np.array(data4)
arr4

arr3.shape # qator va ustunlar sonini ko'rsatadi (qator,ustun)

arr4.size

arr5=np.zeros((2,4)) # Barcha elementlari 0 ga teng (2,4)
arr5

arr6=np.ones((2,4)) # barcha elementlari 1 ga teng (2,4)
arr6

arr7=np.arange(4,21,2) # 4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massivga joylab beradi
arr7

arr8=np.arange(20) # 0 dan 19gacha bo'lgan qiymatlarni 1 qadam bilan massivga joylab beradi
arr8

"""#1 o'lchamli massiv:
### Tuzilishi: Elementlar bir qator (yoki bitta o'lcham) shaklida joylashadi. Bu massiv chiziqli ma'lumotlarni saqlaydi.
#2 o'lchamli massiv:
### Tuzilishi: Elementlar qator va ustunlar bo'lib joylashadi. Bu massiv jadvalga yoki matritsaga o'xshash ma'lumotlarni saqlaydi.
#3 o'lchamli massiv:
### Tuzilishi:Ma'lumotlar qatlam (depth), qator (row) va ustun (column) ko'rinishida saqlanadi.Har bir qatlam o'z-o'zidan 2D massiv bo'ladi.


"""

arr3 = np.array([
    [[1, 2, 3], [4, 5, 6]],  # 1-qavat
    [[7, 8, 9], [10, 11, 12]]  # 2-qavat
])
arr3

arr3.ndim

